name: chat
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # state managment
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^9.0.0
  path_provider: ^2.0.11
  equatable: ^2.0.5
  get_it: ^7.2.0

  # handel error
  formz: ^0.4.1
  dartz: ^0.10.1

  # date
  intl: ^0.17.0

  dio: ^4.0.6
  dash_chat_2: ^0.0.15

  # real Time
  pusher_client: ^2.0.0
  laravel_echo:
    git:
      url: "https://github.com/kakajansh/echo.git"
      ref: master


dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter 

flutter:
  uses-material-design: true
  assets:
    - assets/images/
